server:
  port: 8080
spring:
  application:
    name: "RetoTecnicoBancolombia"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "database-1.cvaompn0vepv.us-east-1.rds.amazonaws.com"
    username: "postgres"
    password: "bancolombia"
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
adapter:
  restconsumer:
    url: "https://restcountries.com/v3.1/name/"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
