server:
  port: 8080

spring:
  application:
    name: "RetoTecnicoBancolombia"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://rds-reto.cvaompn0vepv.us-east-1.rds.amazonaws.com:5432/rdsreto"
    username: "postgres"
    password: "bancolombia"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"

adapter:
  restconsumer:
    url: "https://restcountries.com/v3.1/name/"

management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
  endpoint:
    health:
      probes:
        enabled: true
